# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VW77dFiY58CgXWQAlTuJmyecdFus6oiu
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

from ultralytics import YOLO

!yolo task=detect mode=predict model=/content/drive/MyDrive/TCC/YOLOResults/best.pt conf=0.25 source="/content/drive/MyDrive/TCC/saida.mp4" save=True

from IPython.display import HTML
from base64 import b64encode
import os

# Input video path
save_path = '/content/runs/detect/predict/saida.avi'

# Compressed video path
compressed_path = "/content/compressed_detect.mp4"

os.system(f"ffmpeg -i {save_path} -vcodec libx264 {compressed_path}")

# Show video
mp4 = open(compressed_path,'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=500 controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)